# Generated by Django 2.2 on 2019-04-30 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cookie',
            fields=[
                ('sold', models.BooleanField(default=False)),
                ('cookie_id', models.AutoField(primary_key=True, serialize=False)),
                ('cookie_type', models.IntegerField(choices=[(1, 'Samoas'), (2, 'Tagalongs'), (3, 'Thin Mints')], default=1)),
                ('price', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BuyOrder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_ordered', models.DateTimeField(default=django.utils.timezone.now)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='product_id', to='homepage.Cookie')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
