# Generated by Django 2.2 on 2019-04-29 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cookie',
            fields=[
                ('cookie_id', models.AutoField(primary_key=True, serialize=False)),
                ('cookie_type', models.IntegerField(choices=[(1, 'Samoas'), (2, 'Tagalongs'), (3, 'Thin Mints')], default=1)),
                ('price', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
