# Generated by Django 2.2 on 2019-04-29 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookie',
            name='cookie_type',
            field=models.IntegerField(choices=[(1, 'Samoas'), (2, 'Tagalongs'), (3, 'Thin Mints')], default=1),
        ),
    ]
