# Generated by Django 2.2 on 2019-04-30 16:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_buyorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyorder',
            name='date_ordered',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
