# Generated by Django 2.2 on 2019-04-30 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20190430_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyorder',
            name='cookie_id',
        ),
    ]
