# Generated by Django 2.2 on 2019-04-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_buyorder_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookie',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
